In [1]:
from utils import *
from Backpropagation import *
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder

In [2]:
 # load iris data
inputData = load_iris()
target_unencoded = inputData.target
encoder = OneHotEncoder(sparse=False)
reshape = inputData["target"].reshape(len(inputData["target"]), 1)
target = encoder.fit_transform(reshape)

# Define parameters
n_layer = 10
array_neuron_layer = [6,6,6,6,6,6,6,6,6,3]
array_activation = ["sigmoid", "sigmoid", 'sigmoid', "relu","sigmoid","relu", "softmax", "sigmoid", "sigmoid", "sigmoid"]
learning_rate = 0.01
error_threshold = 0.01
max_iter = 300
batch_size = 30
# create model
backprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)

# train model
inputData = inputData["data"].tolist()
target = target.tolist()
backprop.backpropagation(inputData, target)

# save model
backprop.saveModel("model.json")

---------------------
At Epoch 0 Error :  35.102786747999865
---------------------
---------------------
At Epoch 1 Error :  27.270722716500035
---------------------
---------------------
At Epoch 2 Error :  21.7251390570001
---------------------
---------------------
At Epoch 3 Error :  17.675922762
---------------------
---------------------
At Epoch 4 Error :  14.585621116500034
---------------------
---------------------
At Epoch 5 Error :  12.124072532999987
---------------------
---------------------
At Epoch 6 Error :  10.106401136999981
---------------------
---------------------
At Epoch 7 Error :  8.421892437000029
---------------------
---------------------
At Epoch 8 Error :  7.007430585000034
---------------------
---------------------
At Epoch 9 Error :  5.815612544999998
---------------------
---------------------
At Epoch 10 Error :  4.8129457454999836
---------------------
---------------------
At Epoch 11 Error :  3.9720800865000085
---------------------
-------------

In [3]:
#print info
print("Info")
backprop.printModel()
print("-------------------------")

#print result
predicted = backprop.predict(inputData)
print("Predicted Value")
print(predicted)
print()

# print score accuracy
print("Score Accuracy")
print(score_accuracy(predicted, target_unencoded))
print()

Info
Hidden Layer-1 :
Activation Function: sigmoid
Unit : 6
Weight: [[1.79141863e+51 1.79141863e+51 1.79141863e+51 1.79141863e+51]
 [1.79141863e+51 1.79141863e+51 1.79141863e+51 1.79141863e+51]
 [1.79141863e+51 1.79141863e+51 1.79141863e+51 1.79141863e+51]
 [1.79141863e+51 1.79141863e+51 1.79141863e+51 1.79141863e+51]
 [1.79141863e+51 1.79141863e+51 1.79141863e+51 1.79141863e+51]
 [1.79141863e+51 1.79141863e+51 1.79141863e+51 1.79141863e+51]]
Weight Bias: [1.0748511786903228e+52, 1.0748511786903228e+52, 1.0748511786903228e+52, 1.0748511786903228e+52, 1.0748511786903228e+52, 1.0748511786903228e+52]

Hidden Layer-2 :
Activation Function: sigmoid
Unit : 6
Weight: [[1.11972724e+26 1.11972724e+26 1.11972724e+26 1.11972724e+26
  1.11972724e+26 1.11972724e+26]
 [1.11972724e+26 1.11972724e+26 1.11972724e+26 1.11972724e+26
  1.11972724e+26 1.11972724e+26]
 [1.11972724e+26 1.11972724e+26 1.11972724e+26 1.11972724e+26
  1.11972724e+26 1.11972724e+26]
 [1.11972724e+26 1.11972724e+26 1.11972724e+26

# New Model

In [5]:
# Define parameters
n_layer = 10
array_neuron_layer = [6,6,6,6,6,6,6,6,6,3]
array_activation = ["sigmoid", "sigmoid", 'sigmoid', "relu","sigmoid","relu", "softmax", "sigmoid", "sigmoid", "sigmoid"]
learning_rate = 0.01
error_threshold = 0.01
max_iter = 300
batch_size = 30
# create model
newBackprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)
# load models
newBackprop.loadModels("model.json")



In [19]:
 # load iris data
inputData = [[4.0, 1.0, 1.2, 0.4],
 [4.9, 3.0, 1.4, 0.3],
 [2.1, 3.1, 1.3, 0.5],
 [4.6, 2.7, 1.5, 0.6]]
newBackprop.predict(inputData)

[[9.8997e-01 1.0000e-05 3.0000e-05]
 [9.8997e-01 1.0000e-05 3.0000e-05]
 [9.8997e-01 1.0000e-05 3.0000e-05]
 [9.8997e-01 1.0000e-05 3.0000e-05]]


[0, 0, 0, 0]