In [166]:
from utils import *
from Backpropagation import *
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold


# Define Model

In [167]:
 # load iris data
inputData = load_iris()
target_unencoded = inputData.target
encoder = OneHotEncoder(sparse=False)
reshape = inputData["target"].reshape(len(inputData["target"]), 1)
target = encoder.fit_transform(reshape)

# Define parameters
n_layer = 4
array_neuron_layer = [6,6,6,3]
array_activation = ["sigmoid", "softmax", 'relu', "linear"]
learning_rate = 0.001
error_threshold = 0.01
max_iter = 100
batch_size = 30
# create model
backprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)

# Train Model

In [168]:
# split data
X = inputData["data"].tolist()
y = target.tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
backup_X_train = X_train
# train model
backprop.backpropagation(X_train, y_train)

# save model
backprop.saveModel("model.json")


---------------------
At Epoch 0 Error :  842.2995257980011
---------------------
---------------------
At Epoch 1 Error :  468.1228985734998
---------------------
---------------------
At Epoch 2 Error :  204.06395855250025
---------------------
---------------------
At Epoch 3 Error :  128.07588103450013
---------------------
---------------------
At Epoch 4 Error :  94.97188192199971
---------------------
---------------------
At Epoch 5 Error :  76.78222441750005
---------------------
---------------------
At Epoch 6 Error :  65.2837266039998
---------------------
---------------------
At Epoch 7 Error :  57.51205287749993
---------------------
---------------------
At Epoch 8 Error :  52.10622679850003
---------------------
---------------------
At Epoch 9 Error :  48.33450718100011
---------------------
---------------------
At Epoch 10 Error :  45.67208465600003
---------------------
---------------------
At Epoch 11 Error :  43.72020378449996
---------------------
-------------

In [169]:
#print info
print("Info")
backprop.printModel()
print("-------------------------")

#print result
predicted = backprop.predict(X_test)
target_unencoded = [ y_test[x].index(max(y_test[x])) for x in range(len(y_test))]
print("Predicted Value")
print(predicted)
print("Real Value")
print(target_unencoded)
print()

# print score accuracy
print("Score Accuracy")
print(score_accuracy(predicted, target_unencoded))
print()

confusion_matrix = confusion_matrix(predicted, target_unencoded)
print("Our Confusion Matrix")
print(confusion_matrix)
print("Our Confusion Matrix Statistics")
print(confusion_matrix_statistics(confusion_matrix))

# Generate confusion_matrix with sklearn's confusion_matrix
sklearn_confusion_matrix = cm(target_unencoded, predicted)
print("Sklearn Confusion Matrix")
print(sklearn_confusion_matrix)
print("Sklearn Confusion Matrix Statistics")
print("Accuracy:", accuracy_score(target_unencoded, predicted))
# Prevent ill-defined warning in precision and recall
print("Precision:", precision_score(target_unencoded, predicted, average='micro'))
print("Recall:", recall_score(target_unencoded, predicted, average='micro'))
print("F1 Score:", f1_score(target_unencoded, predicted, average='micro'))

Info
Hidden Layer-1 :
Activation Function: sigmoid
Unit : 6
Weight: [[118.95138097 118.72242474 113.92277548 118.31522322]
 [121.87859093 120.11587225 116.03434766 119.2804071 ]
 [129.20438903 132.63016136 120.1012827  128.72444217]
 [129.14025849 127.05006725 121.17169737 128.45506529]
 [129.49005201 128.65400021 120.28347563 128.14103696]
 [119.18473681 120.12442191 114.90808256 118.05145126]]
Weight Bias: [-95.90147, -96.34306000000002, -109.08421000000003, -106.94299999999997, -112.85759999999996, -96.07409000000007]

Hidden Layer-2 :
Activation Function: softmax
Unit : 6
Weight: [[ -0.07446903  -0.43382526   0.37072548   0.65582322   1.11959093
   -0.74272775]
 [  0.88210766  -0.0875329   -1.65570097   1.64542136  -1.8283073
    0.19015217]
 [ -8.16789151 -10.36348275  -9.19220263  -7.11943471  -8.08464799
   -8.92019979]
 [ 10.69236563  12.94962696  12.09812681  12.95341191  13.15082256
   12.16514126]
 [  1.46787117   4.59650746   1.55239313   2.3781447    3.0125859
    2.265170

# 10 fold cross validation

In [170]:
kf = KFold(n_splits=10, shuffle=True)
for train_index, test_index in kf.split(inputData["data"]):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = inputData["data"][train_index], inputData["data"][test_index]
    y_train, y_test = target[train_index], target[test_index]

    X_train = X_train.tolist()
    X_test = X_test.tolist()
    y_train = y_train.tolist()
    y_test = y_test.tolist()

    backprop.backpropagation(X_train, y_train)
    #print result
    predicted = backprop.predict(X_test)
    target_unencoded = [ y_test[x].index(max(y_test[x])) for x in range(len(y_test))]
    print("Predicted Value")
    print(predicted)
    print("Real Value")
    print(target_unencoded)
    print()

    # print score accuracy
    print("Score Accuracy")
    print(score_accuracy(predicted, target_unencoded))
    print()
    print("Accuracy:", accuracy_score(target_unencoded, predicted))
    # Prevent ill-defined warning in precision and recall
    print("Precision:", precision_score(target_unencoded, predicted, average='micro'))
    print("Recall:", recall_score(target_unencoded, predicted, average='micro'))
    print("F1 Score:", f1_score(target_unencoded, predicted, average='micro'))


TRAIN: [  0   1   3   4   5   6   7   8   9  11  12  14  15  16  17  18  19  21
  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  48  49  50  51  52  54  55  56  57  58
  61  62  64  65  66  67  68  69  70  71  73  74  75  76  77  78  79  80
  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  99
 100 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 119
 121 122 123 124 125 126 127 128 129 130 131 133 134 135 136 137 138 139
 140 141 142 143 145 146 147 148 149] TEST: [  2  10  13  20  53  59  60  63  72  98 101 118 120 132 144]
---------------------
At Epoch 0 Error :  17.121347300999965
---------------------
---------------------
At Epoch 1 Error :  11.113787872500005
---------------------
---------------------
At Epoch 2 Error :  8.559375814500003
---------------------
---------------------
At Epoch 3 Error :  6.578539775999985
---------------------
---------------------
At Epoch 4 Error :  5.06

# New Model and Data

In [171]:
# Define parameters
n_layer = 4
array_neuron_layer = [6,6,6,3]
array_activation = ["sigmoid", "softmax", 'relu', "linear"]
learning_rate = 0.001
error_threshold = 0.01
max_iter = 100
batch_size = 30
# create model
newBackprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)
# load models
newBackprop.loadModels("model.json")



In [172]:
 # load iris data
X_data = [[4.0, 1.0, 1.2, 0.4],
 [4.9, 3.0, 1.4, 0.3],
 [2.1, 3.1, 1.3, 0.5],
 [4.6, 2.7, 1.5, 0.6]]
newBackprop.predict(X_data)

[[0.48106 0.18044 0.31499]
 [0.48106 0.18044 0.31499]
 [0.48106 0.18044 0.31499]
 [0.48106 0.18044 0.31499]]


[0, 0, 0, 0]