In [49]:
from utils import *
from Backpropagation import *
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

# Define Model

In [50]:
 # load iris data
inputData = load_iris()
target_unencoded = inputData.target
encoder = OneHotEncoder(sparse=False)
reshape = inputData["target"].reshape(len(inputData["target"]), 1)
target = encoder.fit_transform(reshape)

# Define parameters
n_layer = 10
array_neuron_layer = [6,6,6,6,6,6,6,6,6,3]
array_activation = ["sigmoid", "sigmoid", 'sigmoid', "relu","sigmoid","relu", "softmax", "sigmoid", "sigmoid", "sigmoid"]
learning_rate = 0.001
error_threshold = 0.01
max_iter = 10
batch_size = 30
# create model
backprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)

# Train Model

In [51]:
# split data
X = inputData["data"].tolist()
y = target.tolist()

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# train model
backprop.backpropagation(X_train, y_train)

# save model
backprop.saveModel("model.json")

---------------------
At Epoch 0 Error :  39.08978612000003
---------------------
---------------------
At Epoch 1 Error :  39.070539771500066
---------------------
---------------------
At Epoch 2 Error :  39.05476712049999
---------------------
---------------------
At Epoch 3 Error :  39.04234519550015
---------------------
---------------------
At Epoch 4 Error :  39.03345365800004
---------------------
---------------------
At Epoch 5 Error :  39.02790502800002
---------------------
---------------------
At Epoch 6 Error :  39.025273210499925
---------------------
---------------------
At Epoch 7 Error :  39.02553759699996
---------------------
---------------------
At Epoch 8 Error :  39.02871842199996
---------------------
---------------------
At Epoch 9 Error :  39.03439536199997
---------------------


In [52]:
#print info
print("Info")
backprop.printModel()
print("-------------------------")

#print result
predicted = backprop.predict(X_test)
target_unencoded = [ y_test[x].index(max(y_test[x])) for x in range(len(y_test))]
print("Predicted Value")
print(predicted)
print("Real Value")
print(target_unencoded)
print()

# print score accuracy
print("Score Accuracy")
print(score_accuracy(predicted, target_unencoded))
print()

confusion_matrix = confusion_matrix(predicted, target_unencoded)
print("Our Confusion Matrix")
print(confusion_matrix)
print("Our Confusion Matrix Statistics")
print(confusion_matrix_statistics(confusion_matrix))

# Generate confusion_matrix with sklearn's confusion_matrix
sklearn_confusion_matrix = cm(target_unencoded, predicted)
print("Sklearn Confusion Matrix")
print(sklearn_confusion_matrix)
print("Sklearn Confusion Matrix Statistics")
print("Accuracy:", accuracy_score(target_unencoded, predicted))
# Prevent ill-defined warning in precision and recall
print("Precision:", precision_score(target_unencoded, predicted, average='weighted'))
print("Recall:", recall_score(target_unencoded, predicted, average='weighted'))
print("F1 Score:", f1_score(target_unencoded, predicted, average='macro'))

print()

Info
Hidden Layer-1 :
Activation Function: sigmoid
Unit : 6
Weight: [[-0.07866903 -0.44112526  0.37072548  0.65582322]
 [ 1.11809093 -0.74472775  0.65159766 -0.3180429 ]
 [-1.87741097  1.43006136 -2.0588173  -0.04035783]
 [ 0.40980849 -1.78538275 -0.61475263  1.45801529]
 [ 0.50575201 -0.32064979 -1.57247437  0.68528696]
 [-0.16821319  0.68632191  0.88598256 -0.09969874]]
Weight Bias: [-0.05310000000000005, 0.04193999999999999, -0.0011399999999999971, -0.029119999999999997, 0.03999, -0.004249999999999999]

Hidden Layer-2 :
Activation Function: sigmoid
Unit : 6
Weight: [[-0.06599903 -0.41898526  0.37632548  0.66982322  1.14059093 -0.72851775]
 [ 0.64249766 -0.3334429  -1.89181097  1.39979136 -2.0810073  -0.05540783]
 [ 0.40997849 -1.78477275 -0.61475263  1.45934529  0.49455201 -0.34148979]
 [-1.56638437  0.69640696 -0.16391319  0.69977191  0.90257256 -0.08800874]
 [-1.26247883  1.86328746 -1.17732687 -0.3547953   0.2769859  -0.46811937]
 [ 0.55764106 -0.54044709  1.76948469  1.70768292 

F:\Program Files\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# New Model and Data

In [53]:
# Define parameters
n_layer = 10
array_neuron_layer = [6,6,6,6,6,6,6,6,6,3]
array_activation = ["sigmoid", "sigmoid", 'sigmoid', "relu","sigmoid","relu", "softmax", "sigmoid", "sigmoid", "sigmoid"]
learning_rate = 0.001
error_threshold = 0.01
max_iter = 300
batch_size = 30
# create model
newBackprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)
# load models
newBackprop.loadModels("model.json")



In [54]:
 # load iris data
X_data = [[4.0, 1.0, 1.2, 0.4],
 [4.9, 3.0, 1.4, 0.3],
 [2.1, 3.1, 1.3, 0.5],
 [4.6, 2.7, 1.5, 0.6]]
newBackprop.predict(X_data)

[[0.41266 0.26438 0.28239]
 [0.41266 0.26438 0.28239]
 [0.41266 0.26438 0.28239]
 [0.41266 0.26438 0.28239]]


[0, 0, 0, 0]