In [6]:
from utils import *
from Backpropagation import *
from sklearn.datasets import load_iris
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix as cm
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold

# Define Model

In [7]:
# load iris data
inputData = load_iris()
target_unencoded = inputData.target
encoder = OneHotEncoder(sparse=False)
reshape = inputData["target"].reshape(len(inputData["target"]), 1)
target = encoder.fit_transform(reshape)

# Define parameters
n_layer = 5
array_neuron_layer = [16,8,4, 3,3]
array_activation = ["linear", "relu", 'linear', "relu", "sigmoid"]
learning_rate = 0.001
error_threshold = 0.01
max_iter = 500
batch_size = 1

# create model
backprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)

# Train Model

In [8]:
# NOMOR 3
# split data
X = inputData["data"].tolist()
y = target.tolist()

# X, y, target_unencoded = shuffle(X, y, target_unencoded)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=499)
X_test_backup = X_test
y_test_backup = y_test

# train model
backprop.backpropagation(X_train, y_train)

# save model
backprop.saveModel("model.json")


In [9]:
#print info
print("Info")
backprop.printModel()
print("-------------------------")

Info
Hidden Layer-1 :
Activation Function: linear
Unit : 16
Weight: [[ 0.06914969  0.22124319  0.65427393 -0.25394524]
 [-0.51149293  0.15604353  0.63573238  0.4057215 ]
 [ 0.01825613 -0.60773087 -1.00405532  0.02364935]
 [-0.74610706 -0.82618157  0.7564736  -0.0359172 ]
 [ 0.15309692  0.37572612 -0.09334382  0.3721276 ]
 [ 0.39374118  0.68222965 -0.48799366 -0.06353908]
 [ 0.53046126  0.06483712  0.2316939   0.08103741]
 [-0.95825638 -0.24777963  0.04419535  0.3643026 ]
 [-0.17914014 -0.51132698 -0.69808165  0.8106442 ]
 [ 0.41678617  0.51151291  0.20152617 -0.0186063 ]
 [ 0.6707556  -0.42998049  0.58324488 -0.06948292]
 [-0.29881035 -0.60234968  0.43501376  0.31220531]
 [-0.05263326 -0.464382   -0.08839386  0.33379973]
 [ 0.03989319  0.62577634 -0.87003296 -0.05259627]
 [ 0.52726616 -0.39882955 -0.73901165  0.46076646]
 [ 0.57824331 -0.19014718  0.14769618  0.38861605]]
Weight Bias: [0.002257982280072729, -0.0012724343971754568, 0.0013357817409619759, -0.009609588894098893, -0.004009

In [10]:
#print result
predicted = backprop.predict(X_test)
target_unencoded = [ y_test[x].index(max(y_test[x])) for x in range(len(y_test))]
print("Predicted Value")
print(predicted)
print("Real Value")
print(target_unencoded)
print()

# print score accuracy
print("Score Accuracy")
print(score_accuracy(predicted, target_unencoded))
print()

confusion_matrix = confusion_matrix(predicted, target_unencoded)
print("Our Confusion Matrix")
print(confusion_matrix)
print("Our Confusion Matrix Statistics")
print(confusion_matrix_statistics(confusion_matrix))

# Generate confusion_matrix with sklearn's confusion_matrix
sklearn_confusion_matrix = cm(target_unencoded, predicted)
print("Sklearn Confusion Matrix")
print(sklearn_confusion_matrix)
print("Sklearn Confusion Matrix Statistics")
print("Accuracy:", accuracy_score(target_unencoded, predicted))
# Prevent ill-defined warning in precision and recall
print("Precision:", precision_score(target_unencoded, predicted, average='micro'))
print("Recall:", recall_score(target_unencoded, predicted, average='micro'))
print("F1 Score:", f1_score(target_unencoded, predicted, average='micro'))

Predicted Value
[2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2, 0, 2, 0]
Real Value
[1, 0, 1, 0, 1, 1, 0, 2, 1, 2, 0, 1, 0, 1, 0]

Score Accuracy
0.5333333333333333

Our Confusion Matrix
[[0, 0, 0], [0, 6, 0], [7, 0, 2]]
Our Confusion Matrix Statistics
[0.631578947368421, 0.5333333333333333, 0.5333333333333333, 0.5333333333333333]
Sklearn Confusion Matrix
[[6 0 0]
 [0 0 7]
 [0 0 2]]
Sklearn Confusion Matrix Statistics
Accuracy: 0.5333333333333333
Precision: 0.5333333333333333
Recall: 0.5333333333333333
F1 Score: 0.5333333333333333


# 10 fold cross validation

In [11]:
kf = KFold(n_splits=10, shuffle=True)
for train_index, test_index in kf.split(inputData["data"]):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = inputData["data"][train_index], inputData["data"][test_index]
    y_train, y_test = target[train_index], target[test_index]

    X_train = X_train.tolist()
    X_test = X_test.tolist()
    y_train = y_train.tolist()
    y_test = y_test.tolist()

    backprop.backpropagation(X_train, y_train)
    #print result
    predicted = backprop.predict(X_test)
    target_unencoded = [ y_test[x].index(max(y_test[x])) for x in range(len(y_test))]
    print("Predicted Value")
    print(predicted)
    print("Real Value")
    print(target_unencoded)
    print()

    # print score accuracy
    print("Score Accuracy")
    print(score_accuracy(predicted, target_unencoded))
    print()
    print("Accuracy:", accuracy_score(target_unencoded, predicted))
    # Prevent ill-defined warning in precision and recall
    print("Precision:", precision_score(target_unencoded, predicted, average='micro'))
    print("Recall:", recall_score(target_unencoded, predicted, average='micro'))
    print("F1 Score:", f1_score(target_unencoded, predicted, average='micro'))


TRAIN: [  0   1   2   3   4   5   8   9  10  11  12  13  14  15  16  17  18  20
  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
  40  41  42  43  44  45  46  47  49  50  51  52  53  54  55  56  57  58
  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76
  77  78  80  81  82  83  84  85  86  87  88  89  91  92  93  94  95  96
  97  98 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115
 116 119 120 121 123 125 126 127 128 130 131 133 134 135 136 137 138 139
 140 141 142 143 145 146 147 148 149] TEST: [  6   7  19  21  48  79  90  99 117 118 122 124 129 132 144]
Predicted Value
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Real Value
[0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2]

Score Accuracy
0.5333333333333333

Accuracy: 0.5333333333333333
Precision: 0.5333333333333333
Recall: 0.5333333333333333
F1 Score: 0.5333333333333333
TRAIN: [  0   1   2   4   5   6   7   8   9  10  11  13  14  15  17  19  20  21
  22  23  24  26  27  28  

# New Model and Data

In [ ]:
# Define parameters
n_layer = 5
array_neuron_layer = [16,8,4, 3,3]
array_activation = ["linear", "relu", 'linear', "relu", "sigmoid"]
learning_rate = 0.001
error_threshold = 0.01
max_iter = 300
batch_size = 1

# create model and load
newBackprop = Backpropagation(n_layer = n_layer, array_neuron_layer=array_neuron_layer, array_activation=array_activation, learning_rate=learning_rate, error_threshold=error_threshold, max_iter=max_iter, batch_size=batch_size)
newBackprop.loadModels("model.json")



In [ ]:
predicted = newBackprop.predict(X_test_backup)
target_unencoded = [ y_test_backup[x].index(max(y_test_backup[x])) for x in range(len(y_test_backup))]
print("Predicted Value")
print(predicted)
print("Real Value")
print(target_unencoded)
print()

# print score accuracy
print("Score Accuracy")
print(score_accuracy(predicted, target_unencoded))
print()

confusion_matrix = confusion_matrix(predicted, target_unencoded)
print("Our Confusion Matrix")
print(confusion_matrix)
print("Our Confusion Matrix Statistics")
print(confusion_matrix_statistics(confusion_matrix))